config/routes.rb
Lalo::ItemPicker::Engine.routes.draw do
  resources :collections

  root to: "collections#index"
end

app/models/lalo/item_picker/application_record.rb
module Lalo
  module ItemPicker
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/lalo/item_picker/collection.rb
module Lalo::ItemPicker
  class Collection < ApplicationRecord
    has_many :line_items, dependent: :destroy

    validates :line_items, presence: true

    accepts_nested_attributes_for :line_items, reject_if: :all_blank
  end
end

app/models/lalo/item_picker/line_item.rb
module Lalo::ItemPicker
  class LineItem < ApplicationRecord
    belongs_to :collection
  end
end

app/controllers/lalo/item_picker/application_controller.rb
module Lalo
  module ItemPicker
    class ApplicationController < ActionController::Base
    end
  end
end

app/controllers/lalo/item_picker/collections_controller.rb
module Lalo
  module ItemPicker
    class CollectionsController < ApplicationController
      def index
        @collections = Collection.includes(:line_items).all
      end

      def show
        @collection = Collection.includes(:line_items).find(params[:id])
      end

      def new
        @collection = Collection.new
        @collection.line_items.build
      end

      def create
        @collection = Collection.new(collection_params)

        respond_to do |format|
          if @collection.save
            format.html { redirect_to collection_path(@collection), notice: "Collection was successfully created." }
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end

      private

      def collection_params
        params.require(:collection)
          .permit(:comment, line_items_attributes: [:id, :quantity, :_destroy])
      end
    end
  end
end

app/helpers/lalo/item_picker/application_helper.rb
module Lalo
  module ItemPicker
    module ApplicationHelper
    end
  end
end

app/views/lalo/item_picker/collections/index.html.erb
<h1>Collection List</h1>

<%= link_to "Add collection", new_collection_path %>

<ul>
  <% @collections.each do |collection| %>
    <% collection.line_items.each do |item| %>
      <li>Item Name: <%= item.quantity %></li>
    <% end %>
    <hr>
  <% end %>
</ul>

app/views/lalo/item_picker/collections/new.html.erb
<%= form_with model: @collection do |f| %>
  <%= f.fields_for :line_items do |fli| %>
    <p>
      <%= fli.label :quantity %>
      <%= fli.number_field :quantity %>
    </p>
  <% end %>

  <p>
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lalo/item_picker/collections/show.html.erb
<% @collection.line_items.each do |item| %>
  <p><%= item.quantity %></p>
<% end %>

app/views/layouts/lalo/item_picker/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lalo item picker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "lalo/item_picker/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>